apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: gitops-service-source
  namespace: openshift-marketplace
spec:
  displayName: 'Gitops Service by Red Hat'
  image: 'quay.io/cbanavik/gitops-operator-catalog:v1.13.3'
  publisher: 'Red Hat Developer'
  sourceType: grpc